swagger: '2.0'
info:
  version: '1.0'
  title: "progettosauri"
  description: Progettosauri SE2 project - API documentation
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
host: progettosauri-se2-project.herokuapp.com
basePath: /api/v1
consumes:
- application/json
produces:
- application/json

tags:
  - name: "User Management"
  - name: "Exams"
  - name: "Tasks"
  - name: "Classes"
  - name: "Task Groups"

paths:
########################################################################   Users
  /users:
    # Sign Up
    post:
      summary: Register a new user
      tags:
        - "User Management"
      responses:
        201:
          description: Success, user has been created
        400:
          description: Invalid parameters

  /users/{user_id}:
    # User details
    get:
      summary: Get details about a user
      parameters:
        - in: path
          name: user_id
          required: true
          type: integer
          minimum: 1
          description: Id of the desired user
      tags:
        - "User Management"
      responses:
        200:
          description: Success
        400:
          description: Bad parameter
        404:
          description: User does not exist

    # Edit user details
    put:
      summary: Edit a user
      parameters:
        - in: path
          name: user_id
          required: true
          type: integer
          minimum: 1
          description: Parameter description in Markdown.
      tags:
        - "User Management"
      responses:
        200:
          description: Success
        400:
          description: Bad parameter
        403:
          description: Permission denied
        404:
          description: User does not exist

    # Delete user
    delete:
      summary: Delete a user
      parameters:
        - in: path
          name: user_id
          required: true
          type: integer
          minimum: 1
          description: Parameter description in Markdown.
      tags:
        - "User Management"
      responses:
        200:
          description: Success
        400:
          description: Bad parameter
        403:
          description: Permission denied
        404:
          description: User does not exist

########################################################################   Exams
  /exams:
    # Visualize exams
    get:
      summary: "View your exams"
      description: "View both the exams you have created, the ones you can participate in and those you have completed"
      tags:
        - "Exams"
      responses:
        200:
          description: Success

    # Create an exam
    post:
      summary: "Create an exam"
      description: "Create an exam from a set of tasks"
      tags:
        - "Exams"
      responses:
        201:
          description: Success, exam has been created
        400:
          description: Bad parameter

  /exams/{exam_id}:
    # Info about an exam
    get:
      summary: "Get info about an exam"
      parameters:
        - in: path
          name: exam_id
          required: true
          type: integer
          minimum: 1
          description: Id of the exam
      tags:
        - "Exams"
      responses:
        200:
          description: Success
        400:
          description: Bad parameter
        403:
          description: Permission denied
        404:
          description: Exam does not exist

    # Update info about an exam
    put:
      summary: "Update info about an exam"
      parameters:
        - in: path
          name: exam_id
          required: true
          type: integer
          minimum: 1
          description: Id of the exam
      tags:
        - "Exams"
      responses:
        200:
          description: Success
        400:
          description: Bad parameter
        403:
          description: Permission denied
        404:
          description: Exam does not exist

    # Delete an exam
    delete:
      summary: "Delete an exam"
      parameters:
        - in: path
          name: exam_id
          required: true
          type: integer
          minimum: 1
          description: Id of the exam
      tags:
        - "Exams"
      responses:
        200:
          description: Success
        400:
          description: Bad parameter
        403:
          description: Permission denied
        404:
          description: Exam does not exist

  /exams/{exam_id}/tasks:
    # Get the evaluation for an exam
    get:
      summary: "View the contents of an exam"
      description: "View the contents of the specified exam. If called by a students, the exam is considered to be started."
      parameters:
        - in: path
          name: exam_id
          required: true
          type: integer
          minimum: 1
          description: Id of the exam
      tags:
        - "Exams"
      responses:
        200:
          description: Success
        400:
          description: Bad parameter
        403:
          description: Permission denied
        404:
          description: Exam does not exist

  /exams/{exam_id}/evaluation:
    # Get the evaluation for an exam
    get:
      summary: "View the evaluation of an exam"
      description: "View the evaluation of the specified exam. If called by the exam creator returns every student's evaluation"
      parameters:
        - in: path
          name: exam_id
          required: true
          type: integer
          minimum: 1
          description: Id of the exam
      tags:
        - "Exams"
      responses:
        200:
          description: Success
        400:
          description: Bad parameter
        403:
          description: Permission denied
        404:
          description: Exam does not exist

    # Evaluate an exam's answers
    post:
      summary: "Submit an evaluation for an exam"
      description: "Submit an evaluation for an exam"
      parameters:
        - in: path
          name: exam_id
          required: true
          type: integer
          minimum: 1
          description: Id of the exam
      tags:
        - "Exams"
      responses:
        200:
          description: Success
        400:
          description: Bad parameter
        403:
          description: Permission denied
        404:
          description: Exam does not exist

    # Modify the evaluation for an exam
    put:
      summary: "Modify an evaluation for an exam"
      parameters:
        - in: path
          name: exam_id
          required: true
          type: integer
          minimum: 1
          description: Id of the exam
      tags:
        - "Exams"
      responses:
        200:
          description: Success
        400:
          description: Bad parameter
        403:
          description: Permission denied
        404:
          description: Exam does not exist

  /exams/{exam_id}/answers:
    # Get the answers for an exam
    get:
      summary: "View the answers of an exam"
      description: "If called by a student returns his own answers. If called by the exam creator returns every student's answers."
      parameters:
        - in: path
          name: exam_id
          required: true
          type: integer
          minimum: 1
          description: Id of the exam
      tags:
        - "Exams"
      responses:
        200:
          description: Success
        400:
          description: Bad parameter
        403:
          description: Permission denied
        404:
          description: Exam does not exist

    # Submit answers to an exam
    post:
      summary: "Send answers of an exam"
      description: "Send answers of an exam"
      parameters:
        - in: path
          name: exam_id
          required: true
          type: integer
          minimum: 1
          description: Id of the exam
      tags:
        - "Exams"
      responses:
        201:
          description: Success, submitted
        400:
          description: Bad parameter
        403:
          description: Permission denied
        404:
          description: Exam does not exist

    # Modify answers to an exam
    put:
      summary: "Modify answers of an exam"
      parameters:
        - in: path
          name: exam_id
          required: true
          type: integer
          minimum: 1
          description: Id of the exam
      tags:
        - "Exams"
      responses:
        201:
          description: Success, submitted
        400:
          description: Bad parameter
        403:
          description: Permission denied
        404:
          description: Exam does not exist

########################################################################   Tasks
  /tasks:
    # Visualize available tasks
    get:
      summary: "View tasks created by and shared with the logged user"
      tags:
        - "Tasks"
      responses:
        200:
          description: Success
        400:
          description: Bad parameter

    # Create tasks
    post:
      summary: "Create a task"
      tags:
        - "Tasks"
      responses:
        201:
          description: Success, task has been created
        400:
          description: Bad parameters

  /tasks/{task_id}:
    # Visualize a task
    get:
      summary: "View details of a specified task"
      tags:
        - "Tasks"
      parameters:
        - in: path
          name: task_id
          required: true
          type: integer
          minimum: 1
          description: Id of the task
      responses:
        200:
          description: Success
        403:
          description: Permission denied
        404:
          description: Task does not exist

######################################################################   Classes
  /classes:
    # Get classes
    get:
      summary: "Get all classes"
      tags:
        - "Classes"
      responses:
        200:
          description: Success
        403:
          description: Permission denied

    # Create a class
    post:
      summary: "Create a group of students identified as a class"
      tags:
        - "Classes"
      responses:
        201:
          description: Success, created
        400:
          description: Bad parameters

    # Update a class
    put:
      summary: "Update a class of students"
      tags:
        - "Classes"
      responses:
        200:
          description: Success
        400:
          description: Bad parameters

##################################################################   Task Groups
  /task_groups:
    # Create a task Groups
    post:
      summary: "Create a group of tasks"
      tags:
        - "Task Groups"
      responses:
        201:
          description: Success, a task group has been created
        400:
          description: Bad parameters

  /task_groups/{task_group_id}:
    # Add a task to a task group
    put:
      summary: "Add a specified task to a task group"
      tags:
        - "Task Groups"
      parameters:
        - in: path
          name: task_group_id
          required: true
          type: integer
          minimum: 1
          description: Id of the task group
      responses:
        200:
          description: Success
        403:
          description: Permission denied
        404:
          description: Task group does not exist
